name: DeploySelfHostedRunner
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Policies:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Prerequisites
        run: .\connect-azure.ps1 -spPass ${{secrets.SPPASS}} -spName ${{secrets.SPNAME}} -SubscriptionId ${{secrets.SUBSCRIPTIONID}} -TenantId ${{secrets.TENANTID}} -Verbose
        shell: pwsh
      - name: Deploy Self Hosted Runner
        run: New-AzDeployment -Location "West Europe" -TemplateFile '.\main.bicep' -TemplateParameterFile '.\mainParameters.json'
        shell: pwsh